[project]
name = "tensoul-download"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.1.1",
    "python-socks[asyncio]>=2.8.2",
    "tensoul",
    "ujson>=5.11.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]

[tool.uv.sources]
tensoul = { git = "https://github.com/unStatiK/tensoul-py-ng.git" }
